### PR TITLE
New implementation for paragraph/attached modifiers

### PR DESCRIPTION
**Pull request by boltlessengineer**
This PR implements all the **hard** parts for attached modifiers & paragraph parsing with much more recursive-focused way.

Even with lots of nodes, parser size is still just 450k (note that some are not implemented yet)
I'm making a draft PR right now because now all tests are passing :)
there are sitll some more to implement before merging

- [x] free form attached modifier
- [x] title_inline (single line paragraph that doesn't allow attached modifiers to have multiple lines inside)
- [x] verbatim attached modifiers

btw, I initially deleted all non-paragraph nodes in first commit of this PR for ease of the development. Sorry about making a mess with commits. I would make a new PR if you don't like this kind of messy commit history.

### CODE REVIEW

**Comment by boltlessengineer** [comment]
My bad, I forgot including some attached modifiers, including them, parser size is now 813k (excluding inline_math & inline_macro to compare with current version)
But still, all tests passing and free-form attached modifiers included

**Comment by boltlessengineer** [comment]
Only feature left from main branch is link/anchor grammar.
But as they aren't finished in main branch neither, I think this PR is ready for merge now.

Features added:
- all types of both non-verbatim and verbatim attached modifiers
- working link modifiers (both left and right)
- free form attached modifiers

These are all working fine with other existing grammars (or at least, they are passing all current test cases.)

**Comment by boltlessengineer** [comment]
Parser size get quite bigger than before (2.3MB), but with much less `externals` and `conflicts`
Attached modifiers now work without help of external C scanner.

**Comment by vhyrro** [comment]
Looks good to me so far, awesome work! I do wonder how the double attached modifier disqualification is going to work in the scanner, I think that would have to be tested a bit more as well, but I'm happy to merge for now :D

**Pull request merged**
